on:
  push:
    branches:
      - main

name: Release Packaging

jobs:
  release:
    name: Release Packaging
    env:
      PROJECT_NAME_UNDERSCORE: arduino-uno
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Cargo
        run: rustup update
      - name: Install AVR
        run: sudo apt install avr-libc gcc-avr pkg-config avrdude
      - name: Install Ravedude
        run: cargo install ravedude
      - name: Release Build
        run: cargo build --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}
          path: target/release/${{ env.PROJECT_NAME_UNDERSCORE }}
